[package]
name = "shared_pool"
version = "0.1.0"
authors = ["Jorge Israel Peña <jorge.israel.p@gmail.com>"]

[dependencies]
syncbox = "*"
libc = "*"
num_cpus = "*"

[dependencies.eventual]
path = "../eventual"
